baseURL = 'https://donbstringham.com'
languageCode = 'en-us'
title = 'Don B. Stringham'
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Don B. Stringham" # Author's name.
    info = "Full-Stack Sr. Software Engineer" # Author's job title or info.
    description = "Don B. Stringham's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "2022 © Don B. Stringham" # Add footer content
    # fixedbarContent = "&copy; 2022 Don B. stringham" # Add fixedbar content
    # fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/dbs67/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/dbs667/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/don-b-stringham/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "about"
[[menu.main]]
    name = "Resume"
    weight = 2
    url = "resume"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "contact"
[[menu.main]]
    name = "Posts"
    weight = 4
    url  = "posts"